{
 "title": "10.2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU средняя загрузка",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1) /  count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "cpula1"
    },
    {
     "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "cpula5"
    },
    {
     "expr": "avg(node_load15) /  count(count(node_cpu_seconds_total) by (cpu)) * 100",
     "legendFormat": "cpula15"
    }
   ]
  },
  {
   "title": "Памяти доступно",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "HDD доступно",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    }
   ]
  }
 ]
}